module.exports = {
  exclude: [
    "node_modules",
    "node_modules/*",
    "**/node_modules/**/*",
    "**/*.spec.*",
    "**/__tests__/**/*",
    "**/__test_utils__/**/*",
    "**/__fixtures__/**/*",
    "**/testsuite/**/*",
    ".expo",
    ".expo/**/*",
    "**/.expo/**/*",
    ".vscode",
    ".vscode/**/*",
    "**/.vscode/**/*",
  ],
  excludeExternals: true,
  // excludeNotExported: true,
  // excludePrivate: true,
  ignoreCompilerErrors: true,
  includeDeclarations: true,
  includes: "./",
  mode: "modules",
  module: "commonjs",
  moduleResolution: "node",
  out: "docs/api",
  preserveConstEnums: true,
  readme: "README.md",
  src: [
    // "./index.d.ts",
    "./src",
  ],
  stripInternal: false,
  // suppressExcessPropertyErrors: "true",
  // suppressImplicitAnyIndexErrors: "true",
  target: "ES6",
  theme: "default",
  tsconfig: "tsconfig.json",
};
